package com.study.recyclingview_study.counries

data class FlagsList(val flags: MutableList<String> = mutableListOf(
    "https://www.dorogavrim.ru/img/flagi/flag_australia.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_austriya.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_azerbaidgan.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_albaniya.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_algir.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_angola.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_andorra.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_antigua_i_barbudda.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_argentina.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_armeniya.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_afganistan.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_bagamy.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_bangladesh.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_barbados.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_bahrein.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_belarus.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_beliz.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_belgiya.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_benin.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_bolgaria.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_bolivia.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_bosnia_gercegovina.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_botsvana.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_braziliya.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_brunei.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_burkina_faso.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_burundi.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_butan.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_vanuatu.jpg",
    "https://www.dorogavrim.ru/img/flagi/flag_vatikan.jpg",
))